### ISSUE TITLE
Issues about commands

### ISSUE THREAD

**Issue by Jieerbobo** [NineAbyss/GLBench#1]
Thanks for your excellent work!
However, I find that some of the code cannot be executed correctly using your commands. For example, when I run OFA using the following commands, it raises several issues.
```bash
cd models/enhancer/OneForAll/
bash run.sh
```

**Comment by NineAbyss** [comment]
> Thanks for your excellent work! However, I find that some of the code cannot be executed correctly using your commands. For example, when I run OFA using the following commands, it raises several issues.
> 
> ```shell
> cd models/enhancer/OneForAll/
> bash run.sh
> ```

Thank you for your interest in our work! 
Could you please provide more details about the issue? For example, specific error information would help us resolve it together.

**Comment by Jieerbobo** [comment]
```bash
Traceback (most recent call last):
  File "/Users/jie/Documents/Experiment_3/GLBench-main/models/enhancer/OneForAll/run_cdm.py", line 32, in <module>
    from task_constructor import UnifiedTaskConstructor
  File "/Users/jie/Documents/Experiment_3/GLBench-main/models/enhancer/OneForAll/task_constructor.py", line 9, in <module>
    from data.chemmol.gen_data import MolOFADataset
  File "/Users/jie/Documents/Experiment_3/GLBench-main/models/enhancer/OneForAll/data/chemmol/gen_data.py", line 9, in <module>
    from datasets import load_dataset
ModuleNotFoundError: No module named 'datasets'
```

Do I miss some packages? Thanks for your reply!

**Comment by Jieerbobo** [comment]
```bash
Traceback (most recent call last):
  File "/Users/jie/Documents/Experiment_3/GLBench-main/models/enhancer/OneForAll/run_cdm.py", line 32, in <module>
    from task_constructor import UnifiedTaskConstructor
  File "/Users/jie/Documents/Experiment_3/GLBench-main/models/enhancer/OneForAll/task_constructor.py", line 9, in <module>
    from data.chemmol.gen_data import MolOFADataset
  File "/Users/jie/Documents/Experiment_3/GLBench-main/models/enhancer/OneForAll/data/chemmol/gen_data.py", line 11, in <module>
    from data.chemmol.gen_raw_graph import smiles2graph
  File "/Users/jie/Documents/Experiment_3/GLBench-main/models/enhancer/OneForAll/data/chemmol/gen_raw_graph.py", line 11, in <module>
    file1 = open(os.path.join(os.path.dirname(__file__), "id2element.csv"), "r")
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jie/Documents/Experiment_3/GLBench-main/models/enhancer/OneForAll/data/chemmol/id2element.csv'
```

Thanks for your reply!

**Comment by Jieerbobo** [comment]
It seems that the chemmol dataset is not used in your experiment. So how can I avoid some unrelated datasets when running OFA.

**Comment by NineAbyss** [comment]
> It seems that the chemmol dataset is not used in your experiment. So how can I avoid some unrelated datasets when running OFA.

Sorry for the confusion. You can just delete the redundant import and the corresponding content in the code. We have updated the code. Thank you for your help!
